### ISSUE TITLE
Automated email CC

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeCENMigration#1294]
See slack for content

**Comment by Captainkirkdawson** [comment]
Done

**Comment by DeniseColbert** [comment]
Email address still appears as CC (Transcriber Registration)

**Comment by Captainkirkdawson** [comment]
Addressed off line
