### ISSUE TITLE
Problem with sign in process

### ISSUE THREAD

**Issue by geoffj-FUG** [FreeUKGen/FreeCENMigration#1888]
I tried setting up a new userid using [phil.rogers@freeukgenealogy.org.uk](mailto:phil.rogers@freeukgenealogy.org.uk) and it was unsuccessful.

I got a missing page message first (see screenshot 1) and on return got screenshot 2.

Vino, I sent you the screenshots by email.

I got the first sign on email OK. Phil got the messages in the screenshots. There appear to be links to the test3/test version. The system continued to work and Phil was able to set his password and gain access.

Geoff

**Comment by Vino-S** [comment]
I have resolved some of the issues in the Registration Process
1. oppourtunities-to-volunteer-with-freecen page missing: Resolved now. Appname was not downcased
2. Redirect to Welcome to Freecen page issue: Resolved

**Comment by geoffj-FUG** [comment]
@Vino-S Vino

Still have problems

I said I wanted to reset my password.. I selected forgot my password. I entered my freeukgenealogy email address and no UserId. I received a message back "You did not eter an email address:.

Geoff

**Comment by DeniseColbert** [comment]
Vino & Geoff to figure out in a call on 5th Feb

**Comment by geoffj-FUG** [comment]
Updated reset screen working OK.
